@startuml


com.atf.LoginTest -> DriverFactory : Initiate Driver
DriverFactory --> com.atf.LoginTest : return Driver
com.atf.LoginTest -> Application : Go to login page
Application --> com.atf.LoginTest : OK
com.atf.LoginTest -> UiMap : Enter Username
UiMap --> WebDriver : get username web element
WebDriver --> Application : get element by xpath
Application -> WebDriver : return web element
WebDriver --> UiMap : return element
UiMap -> Application : send value

Application --> com.atf.LoginTest : OK
com.atf.LoginTest -> UiMap : Enter Password
UiMap --> WebDriver : get username web element
WebDriver --> Application : get element by xpath
Application -> WebDriver : return web element
WebDriver --> UiMap : return element
UiMap -> Application : send value
Application --> com.atf.LoginTest : OK

com.atf.LoginTest -> UiMap : Click Login
UiMap --> WebDriver : get login button web element
WebDriver --> Application : get element by xpath
Application -> WebDriver : return web element
WebDriver --> UiMap : return element
UiMap -> Application : Click login button
Application --> com.atf.LoginTest : Click provided

com.atf.LoginTest -> JUnit : Validate user is successful logged
JUnit --> Application : Get current URL
Application -> JUnit : Return URL
JUnit --> com.atf.LoginTest : Validate expected vs actual

com.atf.LoginTest -> WebDriver : Close browser
WebDriver --> com.atf.LoginTest : OK

@enduml